In [1]:
# 1)
# Part A
import numpy as np
# Call function
def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)
S = 100
K = 105
r = 0.08
expiry = 0.5
q = 0.0 
n = 1
h = expiry/n
u = 1.3
d = 0.8
fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
# Delta
D = (fu - fd)/(S * (u - d))
# B
B = np.exp(-r * h) * ((u * fd - d * fu) / (u-d))
f = S * D + B
print('Part A')
print(f'Premium: ${f:0.4f}')
print(f'Delta: {D:0.4f}')
print(f'B: {B:0.4f}')
# Part B
# Put function
def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)
fu = putPayoff(u * S, K)
fd = putPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))
B = np.exp(-r * h) * ((u * fd - d * fu) / (u-d))
f = S * D + B
print('\nPart B')
print(f'Premium: ${f:0.4f}')
print(f'Delta: {D:0.4f}')
print(f'B: {B:0.4f}')

Part A
Premium: $11.5684
Delta: 0.5000
B: -38.4316

Part B
Premium: $12.4513
Delta: -0.5000
B: 62.4513


In [2]:
# 2)
# Part A
S = 100
K = 95
r = 0.08
expiry = 0.5
q = 0.0
n = 1
h = expiry / n
 
u = 1.3
d = 0.8

fu = putPayoff(u * S, K)
fd = putPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))
B = np.exp(-r * h) * ((u * fd - d * fu) / (u-d))
f = S * D + B
print('Part A')
print(f'Premium: ${f:0.3f}')

# Part B
callPrice = 17.00

fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))
B = np.exp(-r * h) * ((u * fd - d * fu) / (u-d))
f = S * D + B

A = np.maximum(f - callPrice ,0)

print('\nPart B')
print(f' Arbitrage if call price is $17: ${A:0.4f}')

# Part C
callPrice = 15.50
A = np.maximum(f - callPrice ,0)

print('\nPart C')
print(f' Arbitrage if call price is $15.50: ${A:0.4f}')


Part A
Premium: $7.471

Part B
 Arbitrage if call price is $17: $0.0000

Part C
 Arbitrage if call price is $15.50: $0.6958


In [3]:
# 3)

S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1.0
n = 2
u = 1.3
d = 0.8


def euroBinomialTree(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    Ct = np.zeros((nodes, n+1)) #premium
    St = np.zeros((nodes, n+1)) #dont need
    Dt = np.zeros((nodes, n+1)) #delta
    B = np.zeros((nodes, n+1))  # B
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
        B[i, n] = np.exp(-r * h) * ((u * fd - d * fu) / (u-d))

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print("Premium:")
        print(np.around(Ct, 3))
        print("\n")
        print("Delta:")
        print(np.around(Dt, 3))
        print("\n")
        print("B:")
        print(np.around(B, 3))
        print("\n")            
            
    return Ct[0,0]

callPrc = euroBinomialTree(S, K, r, v, q, T, n, callPayoff, verbose = True)


## need premium, delta, B

#B = np.exp(-r * h) * ((u * fd - d * fu) / (u-d))

[[100.    128.677 165.577]
 [  0.     84.187 108.329]
 [  0.      0.     70.874]]


Premium:
[[19.111 37.402 70.577]
 [ 0.     5.726 13.329]
 [ 0.     0.     0.   ]]


Delta:
[[0.712 1.    0.   ]
 [0.    0.356 0.   ]
 [0.    0.    0.   ]]


B:
[[  0.      0.    -63.633]
 [  0.      0.    -63.633]
 [  0.      0.    -63.633]]




In [4]:
# 4)
S = 100
K = 95
v = 0.30 
r = 0.08
expiry = 1.0
q = 0.0
n = 2 
h = expiry / n
u = 1.3
d = 0.8                     ### Need to change delta for larger tree?
                            ## make tree?
# $80
S = 80 
fu = callPayoff(u * S, K)
fd = callPayoff(d  * S, K)
D = (fu - fd)/(S * (u - d))
print('$80')
print(f'Delta: {D:0.4f}')
# $90
S = 90
fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))
print('\n$90')
print(f'Delta: {D:0.4f}')

# $110
S = 110
fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))
print('\n$110')
print(f'Delta: {D:0.4f}')

# $120
S = 120
fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))
print('\n$120')
print(f'Delta: {D:0.4f}')

# $130
S = 130
fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))
print('\n$130')
print(f'Delta: {D:0.4f}')

$80
Delta: 0.2250

$90
Delta: 0.4889

$110
Delta: 0.8727

$120
Delta: 1.0000

$130
Delta: 1.0000


In [5]:
# 5)

# An American call without a dividend is the same as a European call
S = 100
K = 95
r = 0.08
v = 0.3
q = 0.0
T = 1.0
n = 3
h = T / n

u = np.exp((r - q) * h + v * np.sqrt(h))
d = np.exp((r - q) * h - v * np.sqrt(h))
fu = callPayoff(u * S, K)
fd = callPayoff(d * S, K)
D = (fu - fd)/(S * (u - d))
B = np.exp(-r * h) * ((u * fd - d * fu) / (u-d))

pstar = (np.exp((r - q) * h) - d) / (u - d)

# Part A 
print('Part A')
print(f"The American call Premium: ${pstar : 0.3f}")
print('\nThere is an early exercise option, but this will not be a benifit where there is no didvidend')

# Part B
#print'\nPart B')
#print()

# Part C
#print'\nPart C')
#print()

# Part D
#print'\nPart D')
#print()

Part A
The American call Premium: $ 0.457

There is an early exercise option, but this will not be a benifit where there is no didvidend


In [6]:
# 5)

def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
        
    if verbose:
        print(St)
        print("\n")
        print(Ct)
        print("\n")
                    
            
    return Ct[0,0]
            
putPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff, verbose = True)

# Part A
print('Part A')
print(f'u: {u : 0.3f}')
print(f'd: {d : 0.3f}')

# Part B
print('\nPart B')
print(f"The European Put Premium: {putPrc : 0.3f}")  #Euro put
#Euro call
#Amer put
#Amer call

[[100.         122.12461202 149.1442086  182.1417861 ]
 [  0.          86.36925537 105.47811803 128.8147424 ]
 [  0.           0.          74.59648274  91.10066512]
 [  0.           0.           0.          64.42842668]]


[[ 5.97860511  1.09077967  0.          0.        ]
 [ 0.         10.38654838  2.06235672  0.        ]
 [ 0.          0.         17.90366345  3.89933488]
 [ 0.          0.          0.         30.57157332]]


Part A
u:  1.221
d:  0.864

Part B
The European Put Premium:  5.979
